# Generated by Django 5.2.7 on 2025-11-19 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0006_alter_credito_alumno_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='firmado_admin_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credito',
            name='firmado_admin_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos_firmados_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credito',
            name='firmado_docente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credito',
            name='firmado_docente_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credito',
            name='firmado_docente_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos_firmados_docente', to=settings.AUTH_USER_MODEL),
        ),
    ]
