# Generated by Django 5.2.7 on 2025-11-19 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0007_credito_firmado_admin_en_credito_firmado_admin_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='firmado_alumno_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credito',
            name='firmado_alumno_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos_firmados_alumno', to=settings.AUTH_USER_MODEL),
        ),
    ]
