# Generated by Django 5.2.7 on 2025-11-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_es_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='docente_password',
            field=models.CharField(blank=True, help_text='Contraseña (hasheada) para el portal de docentes', max_length=128),
        ),
    ]
