# Generated by Django 5.2.7 on 2025-11-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_actividad_liberacion_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='convo',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
