# Generated by Django 5.2.7 on 2025-11-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_docente',
            field=models.BooleanField(default=False),
        ),
    ]
