# Generated by Django 5.2.7 on 2025-11-25 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_docente_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='docente_password',
        ),
    ]
